import type { Metadata } from "next";
import { Outfit, Noto_Sans_Thai, JetBrains_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { JsonLd } from "@/components/JsonLd";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { DeferredAmbient } from "@/components/DeferredAmbient";
import { meta, site } from "@/lib/content";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const notoThai = Noto_Sans_Thai({
  variable: "--font-noto-thai",
  subsets: ["thai"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: meta.home.title,
    template: "%s · TheUrk",
  },
  description: meta.home.description,
  applicationName: site.name,
  authors: [{ name: "Urk", url: site.url }],
  creator: "Urk",
  alternates: {
    canonical: "/",
    types: {
      "application/rss+xml": [{ url: "/api/rss", title: "TheUrk Notes" }],
    },
  },
  openGraph: {
    type: "website",
    locale: site.locale,
    url: site.url,
    siteName: site.name,
    title: meta.home.title,
    description: meta.home.description,
    // OG image is generated by app/opengraph-image.tsx (Next file convention)
  },
  twitter: {
    card: "summary_large_image",
    title: meta.home.title,
    description: meta.home.description,
    creator: "@theeark",
    // Twitter image inherits from OG image via file convention
  },
  robots: {
    index: true,
    follow: true,
  },
};

const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": `${site.url}/#person`,
  name: "Urk",
  alternateName: "TheUrk",
  jobTitle: "Solo Founder, Systems Designer",
  description:
    "Solo founder and systems designer from Trat, Thailand. Architect, not builder — designs systems that AI executes.",
  url: site.url,
  sameAs: ["https://x.com/theeark"],
  knowsAbout: [
    "System design",
    "AI orchestration",
    "Solo founding",
    "Product design",
    "Trading systems",
  ],
  address: {
    "@type": "PostalAddress",
    addressLocality: "Trat",
    addressCountry: "TH",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="th"
      className={`${outfit.variable} ${notoThai.variable} ${jetbrainsMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <meta name="color-scheme" content="dark" />
        <meta name="theme-color" content="#0b1120" />
        <link
          rel="preload"
          as="image"
          href="/logo/theurk-logo-mark-144.webp"
          type="image/webp"
          fetchPriority="high"
        />
      </head>
      <body className="min-h-screen flex flex-col antialiased">
        <JsonLd data={personJsonLd} id="ld-person" />
        <DeferredAmbient />
        <Nav />
        <main className="flex flex-1 flex-col">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
